version: '3'

services:
    todoback:
      build: 
        context:  ./todo-app/back-end
        dockerfile: Dockerfile
      # restart: always
      ports:
        - "3001:3001"

    todofront:
      build:
          context: ./todo-app/front-end
          dockerfile: Dockerfile
      depends_on:
          - todoback
      # restart: always
      ports:
        - "3000:3000"
      environment:
        - REACT_APP_API_HOST:  todoback
   
    todotests:
      build:
         context: ./todo-app/tests
         dockerfile: Dockerfile
      environment:
         - FRONT_HOST: todofront
      depends_on:
         - todofront
         - todoback
     